[2024-05-20T15:59:52.924+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T15:59:52.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T15:59:52.934+0000] {logging_mixin.py:188} INFO - [2024-05-20T15:59:52.933+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T15:59:52.977+0000] {processor.py:840} INFO - DAG(s) 'data_loader' retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T15:59:53.141+0000] {logging_mixin.py:188} INFO - [2024-05-20T15:59:53.141+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-20T15:59:53.165+0000] {logging_mixin.py:188} INFO - [2024-05-20T15:59:53.165+0000] {dag.py:3954} INFO - Setting next_dagrun for data_loader to None, run_after=None
[2024-05-20T15:59:53.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.280 seconds
[2024-05-20T16:00:23.368+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:00:23.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:00:23.374+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:00:23.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:00:23.404+0000] {processor.py:840} INFO - DAG(s) 'data_loader' retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:00:23.423+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:00:23.423+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-20T16:00:23.445+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:00:23.444+0000] {dag.py:3954} INFO - Setting next_dagrun for data_loader to None, run_after=None
[2024-05-20T16:00:23.463+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.111 seconds
[2024-05-20T16:00:40.488+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:00:40.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:00:40.492+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:00:40.491+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:00:40.522+0000] {processor.py:840} INFO - DAG(s) 'data_loader' retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:00:40.599+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:00:40.599+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-20T16:00:40.607+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:00:40.607+0000] {dag.py:3118} INFO - Creating ORM DAG for data_loader
[2024-05-20T16:00:40.615+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:00:40.615+0000] {dag.py:3954} INFO - Setting next_dagrun for data_loader to 2022-08-09 01:00:00+00:00, run_after=2022-08-10 01:00:00+00:00
[2024-05-20T16:00:40.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.150 seconds
[2024-05-20T16:01:11.271+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:11.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:01:11.275+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:01:11.274+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:11.291+0000] {processor.py:840} INFO - DAG(s) 'data_loader' retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:11.309+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:01:11.308+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-20T16:01:11.327+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:01:11.327+0000] {dag.py:3954} INFO - Setting next_dagrun for data_loader to 2022-08-10 01:00:00+00:00, run_after=2022-08-11 01:00:00+00:00
[2024-05-20T16:01:11.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.077 seconds
[2024-05-20T16:01:40.306+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:40.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:01:40.310+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:01:40.310+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:40.327+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:01:40.324+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_loader.py", line 26
    )
     ^
SyntaxError: expected ':'
[2024-05-20T16:01:40.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:40.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.049 seconds
[2024-05-20T16:01:46.387+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:46.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:01:46.390+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:01:46.390+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:46.417+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:01:46.417+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_loader.py", line 29
    start_task = DummyOperator(task_id='start', dag=dag)
    ^^^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 18
[2024-05-20T16:01:46.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:46.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.051 seconds
[2024-05-20T16:01:51.542+0000] {processor.py:161} INFO - Started process (PID=276) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:51.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:01:51.550+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:01:51.549+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:51.586+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:01:51.583+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_loader.py", line 18
    with dag as DAG(
                
SyntaxError: cannot assign to function call
[2024-05-20T16:01:51.587+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:51.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.092 seconds
[2024-05-20T16:01:55.766+0000] {processor.py:161} INFO - Started process (PID=294) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:55.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:01:55.769+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:01:55.769+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:55.793+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:01:55.793+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_loader.py", line 18
    with dag as DAG(
                
SyntaxError: cannot assign to function call
[2024-05-20T16:01:55.794+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:01:55.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.046 seconds
[2024-05-20T16:02:26.224+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:02:26.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:02:26.227+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:02:26.226+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:02:26.241+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:02:26.240+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_loader.py", line 18
    with dag as DAG(
                
SyntaxError: cannot assign to function call
[2024-05-20T16:02:26.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:02:26.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.035 seconds
[2024-05-20T16:02:41.186+0000] {processor.py:161} INFO - Started process (PID=389) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:02:41.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:02:41.189+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:02:41.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:02:41.207+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:02:41.205+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_loader.py", line 29, in <module>
    start_task = DummyOperator(task_id='start', dag=dag)
                                                    ^^^
NameError: name 'dag' is not defined
[2024-05-20T16:02:41.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:02:41.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.077 seconds
[2024-05-20T16:02:54.335+0000] {processor.py:161} INFO - Started process (PID=396) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:02:54.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:02:54.338+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:02:54.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:02:54.378+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:02:54.374+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_loader.py", line 29, in <module>
    start_task = DummyOperator(task_id='start', dag=dag)
                                                    ^^^
NameError: name 'dag' is not defined
[2024-05-20T16:02:54.381+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:02:54.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.070 seconds
[2024-05-20T16:03:01.814+0000] {processor.py:161} INFO - Started process (PID=449) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:01.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:03:01.817+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:01.817+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:01.846+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:01.842+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_loader.py", line 44, in <module>
    end_task = DummyOperator(task_id='end', dag=dag)
                                                ^^^
NameError: name 'dag' is not defined
[2024-05-20T16:03:01.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:01.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.055 seconds
[2024-05-20T16:03:05.887+0000] {processor.py:161} INFO - Started process (PID=450) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:05.888+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:03:05.890+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:05.889+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:05.912+0000] {processor.py:840} INFO - DAG(s) 'data_loader' retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:05.988+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:05.987+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-20T16:03:05.995+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:05.995+0000] {dag.py:3118} INFO - Creating ORM DAG for data_loader
[2024-05-20T16:03:06.004+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:06.004+0000] {dag.py:3954} INFO - Setting next_dagrun for data_loader to 2022-08-09 01:00:00+00:00, run_after=2022-08-10 01:00:00+00:00
[2024-05-20T16:03:06.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.140 seconds
[2024-05-20T16:03:08.981+0000] {processor.py:161} INFO - Started process (PID=451) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:08.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:03:08.985+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:08.984+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:09.024+0000] {processor.py:840} INFO - DAG(s) 'data_loader' retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:09.036+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:09.035+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-20T16:03:09.051+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:09.051+0000] {dag.py:3954} INFO - Setting next_dagrun for data_loader to 2022-08-09 01:00:00+00:00, run_after=2022-08-10 01:00:00+00:00
[2024-05-20T16:03:09.069+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.093 seconds
[2024-05-20T16:03:10.079+0000] {processor.py:161} INFO - Started process (PID=452) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:10.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:03:10.082+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:10.082+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:10.104+0000] {processor.py:840} INFO - DAG(s) 'data_loader' retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:10.113+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:10.113+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-20T16:03:10.131+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:10.131+0000] {dag.py:3954} INFO - Setting next_dagrun for data_loader to 2022-08-09 01:00:00+00:00, run_after=2022-08-10 01:00:00+00:00
[2024-05-20T16:03:10.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.073 seconds
[2024-05-20T16:03:40.290+0000] {processor.py:161} INFO - Started process (PID=511) to work on /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:40.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_loader.py for tasks to queue
[2024-05-20T16:03:40.294+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:40.293+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:40.310+0000] {processor.py:840} INFO - DAG(s) 'data_loader' retrieved from /opt/airflow/dags/data_loader.py
[2024-05-20T16:03:40.326+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:40.326+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-20T16:03:40.345+0000] {logging_mixin.py:188} INFO - [2024-05-20T16:03:40.345+0000] {dag.py:3954} INFO - Setting next_dagrun for data_loader to 2022-08-10 01:00:00+00:00, run_after=2022-08-11 01:00:00+00:00
[2024-05-20T16:03:40.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_loader.py took 0.078 seconds
