[2024-05-18T19:33:07.791+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T19:33:07.803+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-18T19:33:07.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-18T19:33:07.811+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-18T19:33:07.822+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2022-08-09 01:00:00+00:00
[2024-05-18T19:33:07.828+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1572) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T19:33:07.829+0000] {standard_task_runner.py:63} INFO - Started process 1574 to run task
[2024-05-18T19:33:07.829+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_loader', 'upload_file', 'scheduled__2022-08-09T01:00:00+00:00', '--job-id', '331', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpoqb93kbi']
[2024-05-18T19:33:07.831+0000] {standard_task_runner.py:91} INFO - Job 331: Subtask upload_file
[2024-05-18T19:33:07.869+0000] {task_command.py:426} INFO - Running <TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [running]> on host b5cbc22da81e
[2024-05-18T19:33:07.927+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_loader' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2022-08-09T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-09T01:00:00+00:00'
[2024-05-18T19:33:07.930+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T19:33:07.937+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T19:33:07.943+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 91, in execute
    hook = GCSHook(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 160, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 252, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2024-05-18T19:33:07.947+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_loader, task_id=upload_file, run_id=scheduled__2022-08-09T01:00:00+00:00, execution_date=20220809T010000, start_date=20240518T193307, end_date=20240518T193307
[2024-05-18T19:33:07.957+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 331 for task upload_file (The conn_id `google_cloud_default` isn't defined; 1574)
[2024-05-18T19:33:07.965+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-18T19:33:07.982+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T19:33:07.984+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T12:27:22.038+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T12:27:22.080+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-19T12:27:22.103+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-19T12:27:22.123+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T12:27:22.160+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2022-08-09 01:00:00+00:00
[2024-05-19T12:27:22.181+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1279) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T12:27:22.183+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_loader', 'upload_file', 'scheduled__2022-08-09T01:00:00+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpqcvaztgp']
[2024-05-19T12:27:22.192+0000] {standard_task_runner.py:63} INFO - Started process 1282 to run task
[2024-05-19T12:27:22.200+0000] {standard_task_runner.py:91} INFO - Job 391: Subtask upload_file
[2024-05-19T12:27:22.344+0000] {task_command.py:426} INFO - Running <TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [running]> on host a464b827924a
[2024-05-19T12:27:22.448+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-19T12:27:22.493+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_loader' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2022-08-09T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-09T01:00:00+00:00'
[2024-05-19T12:27:22.503+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T12:27:22.530+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-19T12:27:22.547+0000] {base.py:84} INFO - Using connection ID 'googlecloud' for task execution.
[2024-05-19T12:27:23.532+0000] {gcs.py:556} INFO - File /opt/***/stg/sales/2022-08-09/file.avro uploaded to src/sales/v1/2022/08/09/file.avro in bucket_de_hw_10_viktor_ostapenko bucket
[2024-05-19T12:27:23.534+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T12:27:23.555+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_loader, task_id=upload_file, run_id=scheduled__2022-08-09T01:00:00+00:00, execution_date=20220809T010000, start_date=20240519T122722, end_date=20240519T122723
[2024-05-19T12:27:23.627+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T12:27:23.656+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T12:27:23.659+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T12:30:06.182+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T12:30:06.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-19T12:30:06.202+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-19T12:30:06.203+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T12:30:06.215+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2022-08-09 01:00:00+00:00
[2024-05-19T12:30:06.221+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1330) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T12:30:06.223+0000] {standard_task_runner.py:63} INFO - Started process 1332 to run task
[2024-05-19T12:30:06.222+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_loader', 'upload_file', 'scheduled__2022-08-09T01:00:00+00:00', '--job-id', '397', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmp77jazrqp']
[2024-05-19T12:30:06.224+0000] {standard_task_runner.py:91} INFO - Job 397: Subtask upload_file
[2024-05-19T12:30:06.266+0000] {task_command.py:426} INFO - Running <TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [running]> on host a464b827924a
[2024-05-19T12:30:06.301+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-19T12:30:06.323+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_loader' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2022-08-09T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-09T01:00:00+00:00'
[2024-05-19T12:30:06.326+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T12:30:06.332+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-19T12:30:06.333+0000] {base.py:84} INFO - Using connection ID 'googlecloud' for task execution.
[2024-05-19T12:30:06.885+0000] {gcs.py:556} INFO - File /opt/***/stg/sales/2022-08-09/file.avro uploaded to src/sales/v1/2022/08/09/file.avro in bucket_de_hw_10_viktor_ostapenko bucket
[2024-05-19T12:30:06.886+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T12:30:06.896+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_loader, task_id=upload_file, run_id=scheduled__2022-08-09T01:00:00+00:00, execution_date=20220809T010000, start_date=20240519T123006, end_date=20240519T123006
[2024-05-19T12:30:06.921+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T12:30:06.936+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T12:30:06.938+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-20T16:00:56.250+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T16:00:56.266+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-20T16:00:56.274+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-20T16:00:56.274+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-20T16:00:56.285+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2022-08-09 01:00:00+00:00
[2024-05-20T16:00:56.293+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-20T16:00:56.294+0000] {standard_task_runner.py:63} INFO - Started process 72 to run task
[2024-05-20T16:00:56.294+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_loader', 'upload_file', 'scheduled__2022-08-09T01:00:00+00:00', '--job-id', '401', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpvjpyqegg']
[2024-05-20T16:00:56.296+0000] {standard_task_runner.py:91} INFO - Job 401: Subtask upload_file
[2024-05-20T16:00:56.332+0000] {task_command.py:426} INFO - Running <TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [running]> on host a464b827924a
[2024-05-20T16:00:56.368+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-20T16:00:56.392+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_loader' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2022-08-09T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-09T01:00:00+00:00'
[2024-05-20T16:00:56.393+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T16:00:56.401+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-20T16:00:56.402+0000] {base.py:84} INFO - Using connection ID 'googlecloud' for task execution.
[2024-05-20T16:00:57.290+0000] {gcs.py:556} INFO - File /opt/***/stg/sales/2022-08-09/file.avro uploaded to src/sales/v1/2022/08/09/file.avro in bucket_de_hw_10_viktor_ostapenko bucket
[2024-05-20T16:00:57.291+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T16:00:57.304+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_loader, task_id=upload_file, run_id=scheduled__2022-08-09T01:00:00+00:00, execution_date=20220809T010000, start_date=20240520T160056, end_date=20240520T160057
[2024-05-20T16:00:57.351+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-20T16:00:57.364+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T16:00:57.365+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-20T16:03:33.987+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T16:03:34.025+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-20T16:03:34.051+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-20T16:03:34.052+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-20T16:03:34.066+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2022-08-09 01:00:00+00:00
[2024-05-20T16:03:34.072+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=111) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-20T16:03:34.074+0000] {standard_task_runner.py:63} INFO - Started process 113 to run task
[2024-05-20T16:03:34.073+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_loader', 'upload_file', 'scheduled__2022-08-09T01:00:00+00:00', '--job-id', '403', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmp0hwug_w3']
[2024-05-20T16:03:34.078+0000] {standard_task_runner.py:91} INFO - Job 403: Subtask upload_file
[2024-05-20T16:03:34.124+0000] {task_command.py:426} INFO - Running <TaskInstance: data_loader.upload_file scheduled__2022-08-09T01:00:00+00:00 [running]> on host a464b827924a
[2024-05-20T16:03:34.169+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-20T16:03:34.196+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_loader' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2022-08-09T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-09T01:00:00+00:00'
[2024-05-20T16:03:34.198+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T16:03:34.203+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-20T16:03:34.205+0000] {base.py:84} INFO - Using connection ID 'googlecloud' for task execution.
[2024-05-20T16:03:34.811+0000] {gcs.py:556} INFO - File /opt/***/stg/sales/2022-08-09/file.avro uploaded to src/sales/v1/2022/08/09/file.avro in bucket_de_hw_10_viktor_ostapenko bucket
[2024-05-20T16:03:34.812+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T16:03:34.819+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_loader, task_id=upload_file, run_id=scheduled__2022-08-09T01:00:00+00:00, execution_date=20220809T010000, start_date=20240520T160334, end_date=20240520T160334
[2024-05-20T16:03:34.852+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-20T16:03:34.859+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
